package pl.kindergate.feature.tasks

/**
 * Normalized letter stroke definitions for the letter-tracing task.
 *
 * Each letter is represented as a list of strokes.
 * Each stroke is a list of (x, y) control points in the range [0.0, 1.0],
 * where (0, 0) = top-left of the bounding box, (1, 1) = bottom-right.
 *
 * Guide points are generated by linear interpolation along the strokes
 * in [LetterTracingTask] and mapped to actual canvas pixel coordinates.
 */
object LetterPaths {

    /** Returns all strokes for the given uppercase letter, or an empty list if unknown. */
    fun strokesFor(letter: Char): List<List<Pair<Float, Float>>> = when (letter.uppercaseChar()) {
        'A' -> listOf(
            listOf(0.5f to 0.05f, 0.1f to 0.95f),
            listOf(0.5f to 0.05f, 0.9f to 0.95f),
            listOf(0.25f to 0.57f, 0.75f to 0.57f),
        )
        'B' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(
                0.15f to 0.05f, 0.65f to 0.05f, 0.85f to 0.18f,
                0.85f to 0.38f, 0.65f to 0.50f, 0.15f to 0.50f,
            ),
            listOf(
                0.15f to 0.50f, 0.70f to 0.50f, 0.90f to 0.65f,
                0.90f to 0.85f, 0.70f to 0.95f, 0.15f to 0.95f,
            ),
        )
        'C' -> listOf(
            listOf(
                0.85f to 0.22f, 0.65f to 0.05f, 0.35f to 0.05f,
                0.10f to 0.25f, 0.10f to 0.75f, 0.35f to 0.95f,
                0.65f to 0.95f, 0.85f to 0.78f,
            ),
        )
        'D' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(
                0.15f to 0.05f, 0.55f to 0.05f, 0.90f to 0.25f,
                0.90f to 0.75f, 0.55f to 0.95f, 0.15f to 0.95f,
            ),
        )
        'E' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(0.15f to 0.05f, 0.85f to 0.05f),
            listOf(0.15f to 0.50f, 0.72f to 0.50f),
            listOf(0.15f to 0.95f, 0.85f to 0.95f),
        )
        'F' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(0.15f to 0.05f, 0.85f to 0.05f),
            listOf(0.15f to 0.50f, 0.72f to 0.50f),
        )
        'G' -> listOf(
            listOf(
                0.85f to 0.22f, 0.65f to 0.05f, 0.35f to 0.05f,
                0.10f to 0.25f, 0.10f to 0.75f, 0.35f to 0.95f,
                0.65f to 0.95f, 0.85f to 0.75f, 0.85f to 0.50f, 0.52f to 0.50f,
            ),
        )
        'H' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(0.85f to 0.05f, 0.85f to 0.95f),
            listOf(0.15f to 0.50f, 0.85f to 0.50f),
        )
        'I' -> listOf(
            listOf(0.50f to 0.05f, 0.50f to 0.95f),
            listOf(0.25f to 0.05f, 0.75f to 0.05f),
            listOf(0.25f to 0.95f, 0.75f to 0.95f),
        )
        'J' -> listOf(
            listOf(0.65f to 0.05f, 0.65f to 0.80f, 0.50f to 0.95f, 0.30f to 0.85f),
            listOf(0.38f to 0.05f, 0.82f to 0.05f),
        )
        'K' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(0.15f to 0.50f, 0.85f to 0.05f),
            listOf(0.15f to 0.50f, 0.85f to 0.95f),
        )
        'L' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(0.15f to 0.95f, 0.85f to 0.95f),
        )
        'M' -> listOf(
            listOf(
                0.10f to 0.95f, 0.10f to 0.05f,
                0.50f to 0.55f, 0.90f to 0.05f, 0.90f to 0.95f,
            ),
        )
        'N' -> listOf(
            listOf(0.15f to 0.95f, 0.15f to 0.05f, 0.85f to 0.95f, 0.85f to 0.05f),
        )
        'O' -> listOf(
            listOf(
                0.50f to 0.05f, 0.25f to 0.05f, 0.05f to 0.28f,
                0.05f to 0.72f, 0.25f to 0.95f, 0.50f to 0.95f,
                0.75f to 0.95f, 0.95f to 0.72f, 0.95f to 0.28f,
                0.75f to 0.05f, 0.50f to 0.05f,
            ),
        )
        'P' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(
                0.15f to 0.05f, 0.65f to 0.05f, 0.85f to 0.20f,
                0.85f to 0.40f, 0.65f to 0.55f, 0.15f to 0.55f,
            ),
        )
        'R' -> listOf(
            listOf(0.15f to 0.05f, 0.15f to 0.95f),
            listOf(
                0.15f to 0.05f, 0.65f to 0.05f, 0.85f to 0.20f,
                0.85f to 0.40f, 0.65f to 0.55f, 0.15f to 0.55f,
            ),
            listOf(0.48f to 0.55f, 0.85f to 0.95f),
        )
        'S' -> listOf(
            listOf(
                0.85f to 0.18f, 0.65f to 0.05f, 0.35f to 0.05f,
                0.15f to 0.22f, 0.15f to 0.42f, 0.35f to 0.50f,
                0.65f to 0.50f, 0.85f to 0.65f, 0.85f to 0.82f,
                0.65f to 0.95f, 0.35f to 0.95f, 0.15f to 0.82f,
            ),
        )
        'T' -> listOf(
            listOf(0.50f to 0.05f, 0.50f to 0.95f),
            listOf(0.10f to 0.05f, 0.90f to 0.05f),
        )
        'U' -> listOf(
            listOf(
                0.15f to 0.05f, 0.15f to 0.75f, 0.25f to 0.92f,
                0.50f to 0.95f, 0.75f to 0.92f, 0.85f to 0.75f, 0.85f to 0.05f,
            ),
        )
        'W' -> listOf(
            listOf(
                0.10f to 0.05f, 0.25f to 0.95f,
                0.50f to 0.55f, 0.75f to 0.95f, 0.90f to 0.05f,
            ),
        )
        'X' -> listOf(
            listOf(0.10f to 0.05f, 0.90f to 0.95f),
            listOf(0.90f to 0.05f, 0.10f to 0.95f),
        )
        'Y' -> listOf(
            listOf(0.10f to 0.05f, 0.50f to 0.52f, 0.90f to 0.05f),
            listOf(0.50f to 0.52f, 0.50f to 0.95f),
        )
        'Z' -> listOf(
            listOf(0.10f to 0.05f, 0.90f to 0.05f),
            listOf(0.90f to 0.05f, 0.10f to 0.95f),
            listOf(0.10f to 0.95f, 0.90f to 0.95f),
        )
        // V and Q are less common in Polish, simple definitions
        'V' -> listOf(
            listOf(0.10f to 0.05f, 0.50f to 0.95f, 0.90f to 0.05f),
        )
        'Q' -> listOf(
            listOf(
                0.50f to 0.05f, 0.25f to 0.05f, 0.05f to 0.28f,
                0.05f to 0.72f, 0.25f to 0.95f, 0.50f to 0.95f,
                0.75f to 0.95f, 0.95f to 0.72f, 0.95f to 0.28f,
                0.75f to 0.05f, 0.50f to 0.05f,
            ),
            listOf(0.60f to 0.72f, 0.90f to 0.95f),
        )
        else -> emptyList()
    }

    /**
     * Generates a dense list of sample points by linearly interpolating each stroke
     * at [samplesPerUnit] points per unit of length.
     * Returned points are still in normalized [0, 1] space.
     */
    fun samplePoints(
        letter: Char,
        samplesPerUnit: Float = 80f,
    ): List<Pair<Float, Float>> {
        val result = mutableListOf<Pair<Float, Float>>()
        for (stroke in strokesFor(letter)) {
            if (stroke.size < 2) continue
            for (seg in 0 until stroke.size - 1) {
                val (x0, y0) = stroke[seg]
                val (x1, y1) = stroke[seg + 1]
                val dx = x1 - x0
                val dy = y1 - y0
                val length = Math.hypot(dx.toDouble(), dy.toDouble()).toFloat()
                val steps = maxOf(2, (length * samplesPerUnit).toInt())
                for (s in 0..steps) {
                    val t = s.toFloat() / steps
                    result += (x0 + dx * t) to (y0 + dy * t)
                }
            }
        }
        return result
    }
}
